# Change these first
owner: swiftwave-org
repo: upptime # The name of this repository

sites:
  - name: Landing Page & Documentation
    url: swiftwave.org
    assignees:
      - tanmoysrt
  - name: Swiftwave Dashboard
    url: dashboard.swiftwave.org
    assignees:
      - tanmoysrt
  - name: API Documentation
    url: https://apidocs.swiftwave.org
    assignees:
      - tanmoysrt
  - name: Secured Proxy
    url: https://proxy.swiftwave.org/status
    assignees:
      - tanmoysrt
  - name: Staging Environment
    url: http://staging.swiftwave.org/stats
    assignees:
      - tanmoysrt

status-website:
  cname: status.swiftwave.org
  logoUrl: https://raw.githubusercontent.com/swiftwave-org/upptime/master/assets/swiftwave-icon.png
  name: SwiftWave
  theme: light
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: GitHub
      href: https://github.com/swiftwave-org
